### ISSUE TITLE
Inserting section marker causes errors

### ISSUE THREAD

**Issue by Sirius902** [sauraen/seq64#13] opened 2020-09-03 02:08 UTC
I'm trying to import a MIDI I extracted from a DS game with vgmtrans and when I import it without any section markers it works just fine, but, whenever I add a marker titled `Section 1` to bar 7 beat 2, for looping purposes, it causes errors such as `Note Off out of order!`, `Note On out of order!`, and `No notes played in section x!`. This leads to certain instruments cutting out at various points. I have the midi attached below with text files containing seq64's output with and without the section marker.
[Vector to the Heavens.zip](https://github.com/sauraen/seq64/files/5165720/Vector.to.the.Heavens.zip)

**Comment by isghj5** [comment] 2020-09-07 20:24
"Note off out of order" is sometimes caused by stacked notes, which confuses seq64's parser. If there is a note within a note, or two notes exactly on top of each other, seq64 cannot handle it and they should be removed or moved to a second channel to play them. I've had two MIDI 's that had those kinds of stacked notes  (bk cathedral and ff9 flameco)

Seq64 console should give you a time stamp for those notes, take that time stamp and divide by 192 (ticks per BAR) (OOT/MM use 48 per quarter bar) and then add one (MIDI bar count starts at 1, not zero) so if your timestamp is 6192, divided by 192 is 32.25, add a bar, and your hidden note should be at midi 33:2 (bars start at 1, bar quarters start at 1 too, so :2 is the 1/4th of a bar, :4 is the 3/4 way not the end of the bar that's 34:0)

Edit: Oh you have a different issue: seq64's midi parser cannot handle loop markers being placed in the middle of a note, and there is no safe place in all of bar 7 of this midi where you can place a marker without it cutting a note into pieces. I've run into several songs that had to have the loop extended so that a safe spot to loop from could be found with a full loop behind it, but you might have to shrink some notes or remove an echo track from this song.

I did find instances of 5 notes going off at once, OOT/MM cannot handle that many notes per channel at the same time (the second track at least should probably be split into a second channel

**Comment by sauraen** [comment] 2020-09-11 04:33
Thanks isghj5 for looking into this. Right, there is one semi-bug in SEQ64 here, that it can't handle section markers (including loop markers) in the middle of notes. It simply assigns the note on to the earlier section, and the note off to the later section, and then gets confused later when it encounters each of them without its matching message. I say this is a "semi-bug" because it's nonsense to try to loop to the middle of a note--if you actually want your sequence to sound good, you would not intentionally write that. However, it is of course a possible input a user could give, and it should be handled better. I'm currently working on substantial changes to SEQ64, and I've marked this as a TODO for me to fix. What I'll do is just have it move the note off to the end of the section (the loop point) and print a warning message.

However, I'll just say, I'm a bit concerned by the description you gave of your process here: "I'm trying to import a MIDI I extracted from a DS game with vgmtrans". While SEQ64 is a MIDI importer to the Audioseq format, it's not intended to be able to import arbitrary MIDIs, it's intended to import MIDIs which were specifically created to the constraints of the Audioseq format. For most cases, these constraints are easy, e.g. no more than 4 notes per channel at once, program (instrument) numbers based on Audiobank rather than General MIDI programs, and so on. But there are also some subtle constraints, such as the quantization in Audioseq being more coarse leading to very short notes which were valid in MIDI before conversion becoming zero-length after conversion. In short, you should not expect to be able to take a MIDI from somewhere and just import it and have no issues. In your case, you actually didn't have issues when you just imported it, you had issues when you edited it in a way that wasn't compatible with Audioseq (though isghj5 also mentioned you had 5 notes per channel, which will also cause notes to get dropped that you may have not noticed).

I appreciate the issue submission and I'll improve the handling of this case. Please do submit issues in the future, even if you're not sure if they're really a software bug or some constraint of the format.

**Comment by Sirius902** [comment] 2020-09-11 04:50
Thank you both for the info! I think in this case, even though my MIDI does not fit all the requirements, the main issue here is probably the section marker inside of a note since the MIDI sounds perfectly fine without the marker.

**Comment by sauraen** [comment] 2021-09-29 05:53
SEQ64 V2.0 has code which will cut off notes at the loop point if they extend across the loop point. This is not fully tested; if it does not work, please reopen and provide a reproducing MIDI file.

**Closed as completed by sauraen** 2021-09-29 05:53 UTC
